In [1]:
import numpy as np
import random

In [2]:
gamma = 0.75
alpha = 0.9
location_states = {'A': 0,
                   'B': 1,
                   'C': 2,
                   'D': 3,
                   'E': 4,
                   'F': 5,
                   'G': 6,
                   'H': 7,
                   'I': 8,
                   'J': 9,
                   'K':10,
                   'L':11}
actions = [0,1,2,3,4,5,6,7,8,9,10,11]
##states  = [0,1,2,3,4,5,6,7,8,9,10,11]
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
              [1,0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,1,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,0],
              [0,1,0,0,0,0,0,0,0,1,0,0],
              [0,0,1,0,0,0,1,1,0,0,0,0],
              [0,0,0,1,0,0,1,0,0,0,0,1],
              [0,0,0,0,1,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0,1,0,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1],
              [0,0,0,0,0,0,0,1,0,0,1,0]])                    
Q = np.array(np.zeros([12,12]))
R_new = np.copy(R)
t = 0

In [3]:
print("Q-val:")
print(Q.astype(int))

Q-val:
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [4]:
state_to_location = {state: location for location, state in location_states.items()}

In [5]:
def route(starting_location, ending_location):
    ending_state = location_states[ending_location]
    R_new[ending_state,ending_state] = 1000
    route = [starting_location]
    next_location = starting_location
    
    for i in range(1000):
        current_state = np.random.randint(0,12)
        playable_actions = []
        for j in range(12):
            if R_new[current_state,j] > 0:
                playable_actions.append(j)
        next_state = np.random.choice(playable_actions)
        TD = R_new[current_state,next_state] + gamma * Q[next_state,np.argmax(Q[next_state,])] - Q[current_state,next_state] 
        Q[current_state,next_state] = Q[current_state,next_state] + alpha*TD
        
    while(next_location!=ending_location):
        starting_state = location_states[starting_location]
        next_state = np.argmax(Q[starting_state,])
        next_location = state_to_location[next_state]
        route.append(next_location)
        starting_location = next_location
    return route

In [7]:
route('E','A')

['E', 'I', 'J', 'F', 'B', 'A']